"use client";

import { useMemo, useState, useTransition } from "react";
import { useI18n } from "@/components/I18nProvider";
import { DEFAULT_CUSTOM_INSTRUCTIONS } from "@/components/create-post/constants";
import { renderStatusMessage, parseTextareaItems } from "@/components/content-automation/helpers";
import { useContentAutomation } from "@/hooks/useContentAutomation";
import { createEmptyBriefingFields, parseStoredCustomInstructions, serializeStoredCustomInstructions } from "@/lib/briefing-builder";
import { getClientRequestErrorMessage } from "@/lib/client/http";
import { generateAutomaticSetting as generateAutomaticSettingService, generateAutomaticSettingsBundle as generateAutomaticSettingsBundleService } from "@/services/frontend/content-system";
import { saveGenerationSettings as saveGenerationSettingsService } from "@/services/frontend/user";
import { AgendaAutomationSection } from "./settings-sections/AgendaAutomationSection";
import { AgendaRulesSection } from "./settings-sections/AgendaRulesSection";
import { AutomationSection } from "./settings-sections/AutomationSection";
import { BriefingActionsBar } from "./settings-sections/BriefingActionsBar";
import { BriefingControlsSection } from "./settings-sections/BriefingControlsSection";
import { BriefingEditorSection } from "./settings-sections/BriefingEditorSection";
import { GeneratedAgendaSection } from "./settings-sections/GeneratedAgendaSection";
import { LanguageSection, PresetLibrarySection } from "./settings-sections/LanguageAndPresetSections";
import { MemorySection } from "./settings-sections/MemorySection";
import { SourcesSection } from "./settings-sections/SourcesSection";
import { StrategySection } from "./settings-sections/StrategySection";
import type { DayLabel, Props } from "./types";
import { DAY_ORDER } from "./utils";

export function ContentAutomationSettings({ initialProfile, initialAgenda, initialTopicsHistory, initialTab = "agenda", initialOutputLanguage = "en", initialCustomInstructions = DEFAULT_CUSTOM_INSTRUCTIONS }: Props) {
  const { dictionary } = useI18n();
  const parsedInitialInstructions = useMemo(() => parseStoredCustomInstructions(initialCustomInstructions), [initialCustomInstructions]);
  const [outputLanguage, setOutputLanguage] = useState(initialOutputLanguage);
  const [briefingMode, setBriefingMode] = useState(parsedInitialInstructions.mode);
  const [guidedBriefingFields, setGuidedBriefingFields] = useState(parsedInitialInstructions.fields);
  const [customInstructions, setCustomInstructions] = useState(parsedInitialInstructions.prompt || DEFAULT_CUSTOM_INSTRUCTIONS);
  const [generationSettingsMessage, setGenerationSettingsMessage] = useState<string | null>(null);
  const [autoSettingKey, setAutoSettingKey] = useState<string | null>(null);
  const [isSavingGenerationSettings, startSavingGenerationSettings] = useTransition();
  const [isAutoGeneratingAllSettings, startAutoGeneratingAllSettings] = useTransition();
  const [expandedDays, setExpandedDays] = useState<Record<DayLabel, boolean>>(Object.fromEntries(DAY_ORDER.map((day, index) => [day, index === 0])) as Record<DayLabel, boolean>);
  const [openPresetPicker, setOpenPresetPicker] = useState<string | null>(null);
  const automation = useContentAutomation({ initialProfile, initialAgenda, initialTopicsHistory, dictionary: { saveSuccess: dictionary.contentAutomation.saveSuccess, saveError: dictionary.contentAutomation.saveError, generateSuccess: dictionary.contentAutomation.generateSuccess, generateError: dictionary.contentAutomation.generateError, clearTopicsHistorySuccess: dictionary.contentAutomation.clearTopicsHistorySuccess, clearTopicsHistoryError: dictionary.contentAutomation.clearTopicsHistoryError } });

  const groupedAgenda = useMemo(() => Array.from(automation.agenda.reduce((groups, item) => { const key = `${item.date}-${item.day}`; const current = groups.get(key); if (current) current.items.push(item); else groups.set(key, { ...item, items: [item] }); return groups; }, new Map<string, any>()).values()), [automation.agenda]);
  const goalPresetItems = useMemo(() => parseTextareaItems(automation.presets.goalPresets), [automation.presets.goalPresets]);
  const contentTypePresetItems = useMemo(() => parseTextareaItems(automation.presets.contentTypePresets), [automation.presets.contentTypePresets]);
  const formatPresetItems = useMemo(() => parseTextareaItems(automation.presets.formatPresets), [automation.presets.formatPresets]);
  const postTimesByDay = useMemo(() => Object.fromEntries(DAY_ORDER.map((day) => [day, parseTextareaItems(automation.daySettings[day].postTimes)])) as Record<DayLabel, string[]>, [automation.daySettings]);
  const guidedBriefingPrompt = useMemo(() => ["You are an expert Instagram content strategist and visual designer.", "Use the following brand briefing as the main operating context for every idea, caption, and visual direction you create.", "Keep the content specific, strategic, commercially useful, and aligned with the brand identity described below.", "", ...Object.entries(guidedBriefingFields).map(([key, value]) => `${key}: ${value || "Not provided."}`)].join("\n"), [guidedBriefingFields]);
  const effectiveCustomInstructions = briefingMode === "guided" ? guidedBriefingPrompt : customInstructions;
  const briefingFieldDefinitions = useMemo(() => [["businessSummary", dictionary.generator.briefingBusinessSummary], ["targetAudience", dictionary.generator.briefingTargetAudience], ["mainObjective", dictionary.generator.briefingMainObjective], ["productsOrServices", dictionary.generator.briefingProductsOrServices], ["brandVoice", dictionary.generator.briefingBrandVoice], ["differentiators", dictionary.generator.briefingDifferentiators], ["painPoints", dictionary.generator.briefingPainPoints], ["contentPillars", dictionary.generator.briefingContentPillars], ["ctaPreference", dictionary.generator.briefingCtaPreference], ["restrictions", dictionary.generator.briefingRestrictions]] as Array<any>, [dictionary]);

  const runAutomaticSetting = async (input: { key: string; target: any; currentValue: string; apply: (value: string) => void; }) => { setGenerationSettingsMessage(null); automation.setError(null); setAutoSettingKey(input.key); try { const json = await generateAutomaticSettingService({ profile: automation.builtProfile, target: input.target, currentValue: input.currentValue }); if (!json.value) throw new Error(dictionary.contentAutomation.generateError); input.apply(json.value); } catch (requestError) { automation.setError(getClientRequestErrorMessage(requestError, dictionary.contentAutomation.generateError, dictionary.common.serverConnectionError)); } finally { setAutoSettingKey((current) => current === input.key ? null : current); } };
  const renderAutoButton = (key: string, onClick: () => Promise<void> | void) => <button type="button" disabled={autoSettingKey === key} onClick={() => { void Promise.resolve(onClick()); }} className="rounded-full border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700 transition hover:border-slate-400 hover:text-ink disabled:cursor-not-allowed disabled:opacity-60">{autoSettingKey === key ? dictionary.contentAutomation.autoGeneratingField : dictionary.contentAutomation.autoGenerateField}</button>;
  const renderPresetPicker = (input: { pickerKey: string; presetsList: string[]; value: string; onAuto: () => Promise<void> | void; onSelectPreset: (preset: string) => void; multiselect?: boolean; }) => <div className="mt-2"><button type="button" onClick={() => setOpenPresetPicker((current) => current === input.pickerKey ? null : input.pickerKey)} className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-slate-300 text-base font-semibold text-slate-700 transition hover:border-slate-400 hover:text-ink" aria-label={dictionary.contentAutomation.chooseSavedPreset}>+</button>{openPresetPicker === input.pickerKey ? <div className="mt-3 rounded-2xl border border-slate-200 bg-white p-3"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">{dictionary.contentAutomation.chooseSavedPreset}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={automation.autoFillKey === input.pickerKey.split("-").slice(0, 2).join("-")} onClick={() => { void Promise.resolve(input.onAuto()).then(() => setOpenPresetPicker(null)); }} className="rounded-full border px-3 py-1 text-xs font-semibold transition disabled:cursor-not-allowed disabled:opacity-60">{automation.autoFillKey === input.pickerKey.split("-").slice(0, 2).join("-") ? dictionary.contentAutomation.autoGeneratingField : dictionary.contentAutomation.autoGenerateField}</button>{input.presetsList.map((preset) => <button key={`${input.pickerKey}-${preset}`} type="button" onClick={() => { input.onSelectPreset(preset); if (!input.multiselect) setOpenPresetPicker(null); }} className="rounded-full border px-3 py-1 text-xs font-semibold transition">{preset}</button>)}</div></div> : null}</div>;

  const saveGenerationSettings = () => startSavingGenerationSettings(async () => { setGenerationSettingsMessage(null); try { const json = await saveGenerationSettingsService({ outputLanguage, customInstructions: serializeStoredCustomInstructions({ mode: briefingMode, fields: guidedBriefingFields, prompt: effectiveCustomInstructions }) }); if (json.outputLanguage) setOutputLanguage(json.outputLanguage); if (typeof json.customInstructions === "string") { const parsed = parseStoredCustomInstructions(json.customInstructions); setBriefingMode(parsed.mode); setGuidedBriefingFields(parsed.fields); setCustomInstructions(parsed.prompt || DEFAULT_CUSTOM_INSTRUCTIONS); } setGenerationSettingsMessage(dictionary.generator.settingsSaved); } catch (requestError) { automation.setError(getClientRequestErrorMessage(requestError, dictionary.generator.settingsSaveError, dictionary.common.serverConnectionError)); } });
  const generateAutomaticSettingsBundle = () => startAutoGeneratingAllSettings(async () => { setGenerationSettingsMessage(null); automation.setError(null); try { const json = await generateAutomaticSettingsBundleService({ profile: automation.builtProfile, customInstructions: effectiveCustomInstructions }); automation.setBrandName(json.brandName ?? automation.brandName); automation.setEditableBrief(json.editableBrief ?? automation.editableBrief); automation.setServices(json.services ?? automation.services); automation.setContentRules(json.contentRules ?? automation.contentRules); automation.setResearchQueries(json.researchQueries ?? automation.researchQueries); automation.setCarouselDefaultStructure(json.carouselDefaultStructure ?? automation.carouselDefaultStructure); automation.updatePreset("goalPresets", json.goalPresets ?? automation.presets.goalPresets); automation.updatePreset("contentTypePresets", json.contentTypePresets ?? automation.presets.contentTypePresets); automation.updatePreset("formatPresets", json.formatPresets ?? automation.presets.formatPresets); if (typeof json.customInstructions === "string") { setBriefingMode("prompt"); setCustomInstructions(json.customInstructions || DEFAULT_CUSTOM_INSTRUCTIONS); } } catch (requestError) { automation.setError(getClientRequestErrorMessage(requestError, dictionary.contentAutomation.generateError, dictionary.common.serverConnectionError)); } });

  const settingsSectionProps = { dictionary, brandName: automation.brandName, setBrandName: automation.setBrandName, editableBrief: automation.editableBrief, setEditableBrief: automation.setEditableBrief, automationLoopEnabled: automation.automationLoopEnabled, setAutomationLoopEnabled: automation.setAutomationLoopEnabled, topicsHistoryCleanupFrequency: automation.topicsHistoryCleanupFrequency, setTopicsHistoryCleanupFrequency: automation.setTopicsHistoryCleanupFrequency, services: automation.services, setServices: automation.setServices, contentRules: automation.contentRules, setContentRules: automation.setContentRules, researchQueries: automation.researchQueries, setResearchQueries: automation.setResearchQueries, carouselDefaultStructure: automation.carouselDefaultStructure, setCarouselDefaultStructure: automation.setCarouselDefaultStructure, presets: automation.presets, updatePreset: automation.updatePreset, renderAutoButton, runAutomaticSetting, saveSettings: automation.saveSettings, generateWeeklyAgenda: automation.generateWeeklyAgenda, isSaving: automation.isSaving, isGenerating: automation.isGenerating, currentTopics: automation.currentTopics, uniqueTopicsHistory: automation.uniqueTopicsHistory, clearTopicsHistory: automation.clearTopicsHistory };
  const agendaSectionProps = { dictionary, daySettings: automation.daySettings, expandedDays, toggleExpandedDay: (day: DayLabel) => setExpandedDays((current) => ({ ...current, [day]: !current[day] })), toggleDay: automation.toggleDay, updateDay: automation.updateDay, updateDayPostTime: automation.updateDayPostTime, updateDayPostIdea: automation.updateDayPostIdea, renderPresetPicker, goalPresetItems, contentTypePresetItems, formatPresetItems, generateAutomaticPostIdea: automation.generateAutomaticPostIdea, postTimesByDay, setAllDaysEnabled: automation.setAllDaysEnabled, saveSettings: automation.saveSettings, generateWeeklyAgenda: automation.generateWeeklyAgenda, isSaving: automation.isSaving, isGenerating: automation.isGenerating, currentTopics: automation.currentTopics, groupedAgenda };

  return <div className="space-y-6">{renderStatusMessage(automation.message, automation.error)}{initialTab === "settings" ? <><BriefingControlsSection dictionary={dictionary} outputLanguage={outputLanguage} setOutputLanguage={setOutputLanguage} briefingMode={briefingMode} setBriefingMode={setBriefingMode} /><BriefingEditorSection dictionary={dictionary} briefingMode={briefingMode} briefingFieldDefinitions={briefingFieldDefinitions} guidedBriefingFields={guidedBriefingFields} updateGuidedBriefingField={(field, value) => setGuidedBriefingFields((current) => ({ ...current, [field]: value }))} guidedBriefingPrompt={guidedBriefingPrompt} customInstructions={customInstructions} setCustomInstructions={setCustomInstructions} renderAutoButton={renderAutoButton} generatePromptInstructions={() => runAutomaticSetting({ key: "customInstructions", target: "customInstructions", currentValue: customInstructions, apply: (value) => { setBriefingMode("prompt"); setCustomInstructions(value); } })} clearGuidedBriefing={() => setGuidedBriefingFields(createEmptyBriefingFields())} /><BriefingActionsBar dictionary={dictionary} generateAutomaticSettingsBundle={generateAutomaticSettingsBundle} isAutoGeneratingAllSettings={isAutoGeneratingAllSettings} saveGenerationSettings={saveGenerationSettings} isSavingGenerationSettings={isSavingGenerationSettings} generationSettingsMessage={generationSettingsMessage} /><StrategySection {...settingsSectionProps} /><div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><SourcesSection {...settingsSectionProps} /><AutomationSection {...settingsSectionProps} /></div><MemorySection {...settingsSectionProps} /><LanguageSection dictionary={dictionary} /><PresetLibrarySection {...settingsSectionProps} /></> : null}{initialTab === "agenda" ? <><AgendaAutomationSection {...agendaSectionProps} /><AgendaRulesSection {...agendaSectionProps} /><GeneratedAgendaSection dictionary={dictionary} groupedAgenda={groupedAgenda} /></> : null}</div>;
}
